name: C/C++ CI

on:
  push:
    branches: [ "master", "con-mod" ]
  pull_request:
    branches: [ "master", "con-mod" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    # Setting up a 32-bit environment
    - name: Set up MSVC for 32-bit builds
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86

    # Configure step (if necessary, adjust or remove if not needed)
    - name: configure
      run: ./configure
    
    # Build step, ensure this is adjusted to compile a 32-bit version
    - name: make
      run: make
    
    # Optional: Run checks if you have tests configured
    - name: make check
      run: make check
    
    # Optional: Perform a distribution check
    - name: make distcheck
      run: make distcheck
    
    # Upload the build artifact
    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: devilution.exe
        path: build/devilution.exe
